# Generated by ThermoLang Compiler for the 'thrml' backend
# This script targets Extropic AI's thrml library using JAX.
import jax
import jax.numpy as jnp
import os
import numpy as np
from thrml import SpinNode, Block, SamplingSchedule, sample_states
from thrml.models import IsingEBM, IsingSamplingProgram, hinton_init

def main():
    print('--- Initializing ThermoLang/thrml Runtime ---')
    # 1. Define Topology (64 spins)
    nodes = [SpinNode() for _ in range(64)]
    biases = jnp.array([-0, -0, -0, -0, -0, -0, -0, -0, -0, -0, -0, -0, -0, -0, -0, -0, -0, -0, -0, -0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=jnp.float32)
    # Reconstructing graph from J matrix
    edges = []
    weights_list = []
    edge_indices_list = []
    edges.append((nodes[0], nodes[1]))
    weights_list.append(-20.286)
    edge_indices_list.append((0, 1))
    edges.append((nodes[0], nodes[8]))
    weights_list.append(-12.8601)
    edge_indices_list.append((0, 8))
    edges.append((nodes[1], nodes[2]))
    weights_list.append(-20.286)
    edge_indices_list.append((1, 2))
    edges.append((nodes[1], nodes[9]))
    weights_list.append(-32)
    edge_indices_list.append((1, 9))
    edges.append((nodes[2], nodes[3]))
    weights_list.append(-12.8601)
    edge_indices_list.append((2, 3))
    edges.append((nodes[3], nodes[4]))
    weights_list.append(-12.8601)
    edge_indices_list.append((3, 4))
    edges.append((nodes[4], nodes[5]))
    weights_list.append(-12.8601)
    edge_indices_list.append((4, 5))
    edges.append((nodes[5], nodes[6]))
    weights_list.append(-12.8601)
    edge_indices_list.append((5, 6))
    edges.append((nodes[6], nodes[7]))
    weights_list.append(-7.36154)
    edge_indices_list.append((6, 7))
    edges.append((nodes[8], nodes[9]))
    weights_list.append(-20.286)
    edge_indices_list.append((8, 9))
    edges.append((nodes[9], nodes[10]))
    weights_list.append(-32)
    edge_indices_list.append((9, 10))
    edges.append((nodes[10], nodes[11]))
    weights_list.append(-32)
    edge_indices_list.append((10, 11))
    edges.append((nodes[10], nodes[18]))
    weights_list.append(-32)
    edge_indices_list.append((10, 18))
    edges.append((nodes[11], nodes[12]))
    weights_list.append(-32)
    edge_indices_list.append((11, 12))
    edges.append((nodes[11], nodes[19]))
    weights_list.append(-20.286)
    edge_indices_list.append((11, 19))
    edges.append((nodes[12], nodes[13]))
    weights_list.append(-20.286)
    edge_indices_list.append((12, 13))
    edges.append((nodes[12], nodes[20]))
    weights_list.append(-40.572)
    edge_indices_list.append((12, 20))
    edges.append((nodes[13], nodes[14]))
    weights_list.append(-20.286)
    edge_indices_list.append((13, 14))
    edges.append((nodes[14], nodes[15]))
    weights_list.append(-20.286)
    edge_indices_list.append((14, 15))
    edges.append((nodes[14], nodes[22]))
    weights_list.append(-20.286)
    edge_indices_list.append((14, 22))
    edges.append((nodes[15], nodes[23]))
    weights_list.append(-25.7202)
    edge_indices_list.append((15, 23))
    edges.append((nodes[16], nodes[17]))
    weights_list.append(-12.8601)
    edge_indices_list.append((16, 17))
    edges.append((nodes[16], nodes[24]))
    weights_list.append(-12.8601)
    edge_indices_list.append((16, 24))
    edges.append((nodes[17], nodes[18]))
    weights_list.append(-20.286)
    edge_indices_list.append((17, 18))
    edges.append((nodes[18], nodes[19]))
    weights_list.append(-20.286)
    edge_indices_list.append((18, 19))
    edges.append((nodes[20], nodes[21]))
    weights_list.append(-25.7202)
    edge_indices_list.append((20, 21))
    edges.append((nodes[21], nodes[22]))
    weights_list.append(-25.7202)
    edge_indices_list.append((21, 22))
    edges.append((nodes[23], nodes[31]))
    weights_list.append(-25.7202)
    edge_indices_list.append((23, 31))
    edges.append((nodes[24], nodes[25]))
    weights_list.append(-25.7202)
    edge_indices_list.append((24, 25))
    edges.append((nodes[25], nodes[26]))
    weights_list.append(-25.7202)
    edge_indices_list.append((25, 26))
    edges.append((nodes[26], nodes[27]))
    weights_list.append(-25.7202)
    edge_indices_list.append((26, 27))
    edges.append((nodes[27], nodes[28]))
    weights_list.append(-25.7202)
    edge_indices_list.append((27, 28))
    edges.append((nodes[28], nodes[29]))
    weights_list.append(-25.7202)
    edge_indices_list.append((28, 29))
    edges.append((nodes[29], nodes[30]))
    weights_list.append(-25.7202)
    edge_indices_list.append((29, 30))
    edges.append((nodes[30], nodes[31]))
    weights_list.append(-25.7202)
    edge_indices_list.append((30, 31))
    weights = jnp.array(weights_list, dtype=jnp.float32)

    # 2. Block Coloring (Derived from ThermoLang GraphColoringPass)
    # Found 3 independent sets (chromatic number).
    free_blocks = [
        Block([nodes[i] for i in [0, 2, 4, 6, 9, 12, 14, 16, 18, 21, 25, 27, 29, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63]]),
        Block([nodes[i] for i in [1, 3, 5, 7, 8, 11, 13, 17, 20, 22, 23, 24, 26, 28, 30]]),
        Block([nodes[i] for i in [10, 15, 19]]),
    ]
    # 3. Temperature configuration
    # Base beta from compiler schedule (kept consistent with previous generator)
    beta = jnp.array(1.0 / 7.48933, dtype=jnp.float32)
    # [INFO] Compiler has baked Noise Shaping (local temperatures) into weights.
    # Telemetry only:
    local_temperatures_ref = jnp.array([0.6, 0.5, 0.6, 0.6, 0.6, 0.6, 0.6, 0.75, 0.6, 0.5, 0.5, 0.5, 0.5, 0.6, 0.5, 0.6, 0.6, 0.6, 0.5, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=jnp.float32)
    model = IsingEBM(nodes, edges, biases, weights, beta)
    program = IsingSamplingProgram(model, free_blocks, clamped_blocks=[])

    # 3b. Schedules
    # Normal schedule: matches the previous behavior closely for anneal (warmup then one sample)
    # Profiling schedule: used ONLY to estimate per-spin variances robustly
    PROFILE_VARIANCE = os.getenv('THERMOLANG_PROFILE_VARIANCE', '0') == '1'
    normal_schedule = SamplingSchedule(n_warmup=10000, n_samples=1, steps_per_sample=10000)
    profile_schedule = SamplingSchedule(n_warmup=2000, n_samples=200, steps_per_sample=200)
    schedule = profile_schedule if PROFILE_VARIANCE else normal_schedule

    key = jax.random.key(4)
    rcheck = jax.random.uniform(key, (3,), dtype=jnp.float32)
    print(f"[SEED_CHECK]: {rcheck.tolist()}")
    k_init, k_samp = jax.random.split(key, 2)
    init_state = hinton_init(k_init, model, free_blocks, ())
    print('Running Thermal Annealing...')
    samples = sample_states(k_samp, program, schedule, init_state, [], [Block(nodes)])

    # 4. Result Processing & Energy Metric
    # IMPORTANT: choose the best (minimum energy) sample across all chains/samples
    # This makes comparisons stable and restores the expected benefit of degree shaping.
    samples_arr = jnp.array(samples)
    # Flatten to [K, N]
    flat = samples_arr.reshape(-1, 64)
    # Convert boolean spins -> Ising spins (+1/-1)
    s_all = 2 * flat.astype(jnp.int8) - 1

    # Re-calculating indices for energy computation
    idx_list = []
    idx_list.append((0, 1))
    idx_list.append((0, 8))
    idx_list.append((1, 2))
    idx_list.append((1, 9))
    idx_list.append((2, 3))
    idx_list.append((3, 4))
    idx_list.append((4, 5))
    idx_list.append((5, 6))
    idx_list.append((6, 7))
    idx_list.append((8, 9))
    idx_list.append((9, 10))
    idx_list.append((10, 11))
    idx_list.append((10, 18))
    idx_list.append((11, 12))
    idx_list.append((11, 19))
    idx_list.append((12, 13))
    idx_list.append((12, 20))
    idx_list.append((13, 14))
    idx_list.append((14, 15))
    idx_list.append((14, 22))
    idx_list.append((15, 23))
    idx_list.append((16, 17))
    idx_list.append((16, 24))
    idx_list.append((17, 18))
    idx_list.append((18, 19))
    idx_list.append((20, 21))
    idx_list.append((21, 22))
    idx_list.append((23, 31))
    idx_list.append((24, 25))
    idx_list.append((25, 26))
    idx_list.append((26, 27))
    idx_list.append((27, 28))
    idx_list.append((28, 29))
    idx_list.append((29, 30))
    idx_list.append((30, 31))
    idx_arr = jnp.array(idx_list)

    # Field energy for each sample: E_field = - sum_i (h_i * s_i)
    E_field_all = -jnp.einsum('i,ki->k', biases, s_all.astype(jnp.float32))
    # Coupling energy for each sample: E_coupling = - sum_edges (J_ij * s_i * s_j)
    if idx_arr.size == 0:
        E_coupling_all = jnp.zeros((s_all.shape[0],), dtype=jnp.float32)
    else:
        s_i = s_all[:, idx_arr[:, 0]].astype(jnp.float32)
        s_j = s_all[:, idx_arr[:, 1]].astype(jnp.float32)
        E_coupling_all = -jnp.sum(weights[None, :] * s_i * s_j, axis=1)
    E_all = E_field_all + E_coupling_all
    best_idx = jnp.argmin(E_all)
    s = s_all[best_idx]
    final_energy = E_all[best_idx]

    final_state_str = ', '.join(map(str, s.tolist()))
    print(f'[FINAL_ENERGY]: {final_energy}')
    print(f'[FINAL_STATE]: [{final_state_str}]')
    try:
        float_samples = s_all.astype(jnp.float32)
        means = jnp.mean(float_samples, axis=0)
        variances = 1.0 - (means ** 2)
        var_str = ','.join([f'{v:.4f}' for v in variances.tolist()])
        print(f'[VARIANCES]: {var_str}')
    except Exception:
        print('[VARIANCES]: error')
    return s

if __name__ == '__main__':
    main()
