# Generated by ThermoLang Compiler for the 'thrml' backend
# This script targets Extropic AI's thrml library using JAX.
import jax
import jax.numpy as jnp
import numpy as np
from thrml import SpinNode, Block, SamplingSchedule, sample_states
from thrml.models import IsingEBM, IsingSamplingProgram, hinton_init

def main():
    print('--- Initializing ThermoLang/thrml Runtime ---')
    # 1. Define Topology (64 spins)
    nodes = [SpinNode() for _ in range(64)]
    biases = jnp.array([-0, -0, -0, -0, -0, -0, -0, -0, -0, -0, -0, -0, -0, -0, -0, -0, -0, -0, -0, -0, -0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=jnp.float32)
    # Reconstructing graph from J matrix
    edges = []
    weights_list = []
    edge_indices_list = []
    edges.append((nodes[0], nodes[1]))
    weights_list.append(20.286)
    edge_indices_list.append((0, 1))
    edges.append((nodes[0], nodes[8]))
    weights_list.append(12.8601)
    edge_indices_list.append((0, 8))
    edges.append((nodes[1], nodes[2]))
    weights_list.append(20.286)
    edge_indices_list.append((1, 2))
    edges.append((nodes[1], nodes[9]))
    weights_list.append(20.286)
    edge_indices_list.append((1, 9))
    edges.append((nodes[2], nodes[3]))
    weights_list.append(12.8601)
    edge_indices_list.append((2, 3))
    edges.append((nodes[3], nodes[4]))
    weights_list.append(12.8601)
    edge_indices_list.append((3, 4))
    edges.append((nodes[4], nodes[5]))
    weights_list.append(12.8601)
    edge_indices_list.append((4, 5))
    edges.append((nodes[5], nodes[6]))
    weights_list.append(12.8601)
    edge_indices_list.append((5, 6))
    edges.append((nodes[6], nodes[7]))
    weights_list.append(7.36154)
    edge_indices_list.append((6, 7))
    edges.append((nodes[8], nodes[9]))
    weights_list.append(12.8601)
    edge_indices_list.append((8, 9))
    edges.append((nodes[10], nodes[11]))
    weights_list.append(11.6124)
    edge_indices_list.append((10, 11))
    edges.append((nodes[11], nodes[12]))
    weights_list.append(32)
    edge_indices_list.append((11, 12))
    edges.append((nodes[11], nodes[19]))
    weights_list.append(32)
    edge_indices_list.append((11, 19))
    edges.append((nodes[12], nodes[13]))
    weights_list.append(32)
    edge_indices_list.append((12, 13))
    edges.append((nodes[12], nodes[20]))
    weights_list.append(20.286)
    edge_indices_list.append((12, 20))
    edges.append((nodes[13], nodes[14]))
    weights_list.append(20.286)
    edge_indices_list.append((13, 14))
    edges.append((nodes[13], nodes[21]))
    weights_list.append(-40.572)
    edge_indices_list.append((13, 21))
    edges.append((nodes[14], nodes[15]))
    weights_list.append(12.8601)
    edge_indices_list.append((14, 15))
    edges.append((nodes[15], nodes[23]))
    weights_list.append(12.8601)
    edge_indices_list.append((15, 23))
    edges.append((nodes[16], nodes[17]))
    weights_list.append(12.8601)
    edge_indices_list.append((16, 17))
    edges.append((nodes[16], nodes[24]))
    weights_list.append(-25.7202)
    edge_indices_list.append((16, 24))
    edges.append((nodes[17], nodes[18]))
    weights_list.append(20.286)
    edge_indices_list.append((17, 18))
    edges.append((nodes[18], nodes[19]))
    weights_list.append(32)
    edge_indices_list.append((18, 19))
    edges.append((nodes[18], nodes[26]))
    weights_list.append(20.286)
    edge_indices_list.append((18, 26))
    edges.append((nodes[19], nodes[20]))
    weights_list.append(20.286)
    edge_indices_list.append((19, 20))
    edges.append((nodes[21], nodes[22]))
    weights_list.append(-25.7202)
    edge_indices_list.append((21, 22))
    edges.append((nodes[22], nodes[23]))
    weights_list.append(-25.7202)
    edge_indices_list.append((22, 23))
    edges.append((nodes[24], nodes[25]))
    weights_list.append(-25.7202)
    edge_indices_list.append((24, 25))
    edges.append((nodes[25], nodes[26]))
    weights_list.append(-25.7202)
    edge_indices_list.append((25, 26))
    weights = jnp.array(weights_list, dtype=jnp.float32)

    # 2. Block Coloring (Derived from ThermoLang GraphColoringPass)
    # Found 3 independent sets (chromatic number).
    free_blocks = [
        Block([nodes[i] for i in [1, 4, 6, 8, 10, 13, 17, 19, 23, 24, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63]]),
        Block([nodes[i] for i in [0, 3, 5, 7, 9, 12, 15, 16, 18, 22, 25]]),
        Block([nodes[i] for i in [2, 11, 14, 20, 21]]),
    ]
    # 3. Temperature configuration
    global_beta = jnp.array(1.0 / 7.61131, dtype=jnp.float32)
    # Noise shaping: bake per-spin beta into biases/weights to avoid broadcasting issues
    local_temperatures = jnp.array([0.6, 0.5, 0.6, 0.6, 0.6, 0.6, 0.6, 0.75, 0.6, 0.6, 0.75, 0.5, 0.5, 0.5, 0.6, 0.6, 0.6, 0.6, 0.5, 0.5, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=jnp.float32)
    beta_vector = global_beta * (1.0 / local_temperatures)
    biases = biases * beta_vector
    edge_inds = jnp.array(edge_indices_list)
    if len(edge_inds) > 0:
        beta_i = beta_vector[edge_inds[:, 0]]
        beta_j = beta_vector[edge_inds[:, 1]]
        edge_scales = jnp.sqrt(beta_i * beta_j)
        weights = weights * edge_scales
    beta = jnp.array(1.0, dtype=jnp.float32)
    print(f'[beta_summary] min={float(jnp.min(beta_vector)):.4f}, max={float(jnp.max(beta_vector)):.4f}')
    model = IsingEBM(nodes, edges, biases, weights, beta)
    program = IsingSamplingProgram(model, free_blocks, clamped_blocks=[])
    schedule = SamplingSchedule(n_warmup=10500, n_samples=1, steps_per_sample=10500)
    key = jax.random.key(0)
    k_init, k_samp = jax.random.split(key, 2)
    init_state = hinton_init(k_init, model, free_blocks, ())
    print(f'Running Thermal Annealing...')
    samples = sample_states(k_samp, program, schedule, init_state, [], [Block(nodes)])

    # 4. Result Processing & Energy Metric
    # We extract the final sample from the first chain
    final_state = samples[0][0]
    # Convert boolean spins (True/False) back to Ising spins (+1/-1)
    # True -> +1, False -> -1
    s = 2 * final_state.astype(jnp.int8) - 1
    # Calculate Field Energy: E_field = - sum(h_i * s_i)
    E_field = -jnp.dot(biases, s)
    # Calculate Coupling Energy: E_coupling = - sum(J_ij * s_i * s_j)
    # We iterate over the edges we constructed earlier
    E_coupling = 0.0
    # Note: thrml edges are (node_u, node_v). We need indices.
    # Since we constructed nodes sequentially, we can map back easily.
    # Re-calculating indices for energy computation
    idx_list = []
    idx_list.append((0, 1))
    idx_list.append((0, 8))
    idx_list.append((1, 2))
    idx_list.append((1, 9))
    idx_list.append((2, 3))
    idx_list.append((3, 4))
    idx_list.append((4, 5))
    idx_list.append((5, 6))
    idx_list.append((6, 7))
    idx_list.append((8, 9))
    idx_list.append((10, 11))
    idx_list.append((11, 12))
    idx_list.append((11, 19))
    idx_list.append((12, 13))
    idx_list.append((12, 20))
    idx_list.append((13, 14))
    idx_list.append((13, 21))
    idx_list.append((14, 15))
    idx_list.append((15, 23))
    idx_list.append((16, 17))
    idx_list.append((16, 24))
    idx_list.append((17, 18))
    idx_list.append((18, 19))
    idx_list.append((18, 26))
    idx_list.append((19, 20))
    idx_list.append((21, 22))
    idx_list.append((22, 23))
    idx_list.append((24, 25))
    idx_list.append((25, 26))
    idx_arr = jnp.array(idx_list)
    if len(idx_arr) > 0:
        s_i = s[idx_arr[:, 0]]
        s_j = s[idx_arr[:, 1]]
        # weights array was defined in step 1
        E_coupling = -jnp.sum(weights * s_i * s_j)
    final_energy = E_field + E_coupling
    final_state_str = ', '.join(map(str, s.tolist()))
    print(f'[FINAL_ENERGY]: {final_energy}')
    print(f'[FINAL_STATE]: [{final_state_str}]')
    try:
        all_samples = jnp.array(samples).reshape(-1, 64)
        float_samples = 2.0 * all_samples.astype(jnp.float32) - 1.0
        means = jnp.mean(float_samples, axis=0)
        variances = 1.0 - (means ** 2)
        var_str = ','.join([f'{v:.4f}' for v in variances.tolist()])
        print(f'[VARIANCES]: {var_str}')
    except Exception as e:
        print(f'[VARIANCES]: error')
    return s

if __name__ == '__main__':
    main()
