# Generated by ThermoLang Compiler
import numpy as np
import sys
np.random.seed(2007)

original_print = print  # Save Python's print function
def debug_print(*args, **kwargs):
    original_print(*args, **kwargs)
    sys.stdout.flush()


def simulate_annealing(energy_function, initial_state, schedule):
    """
    Performs a simulated annealing run.
    """
    try:
        current_state = np.array(initial_state, dtype=np.float32)
        current_energy = energy_function(current_state)

        best_state = np.copy(current_state)
        best_energy = current_energy

        temp = schedule['initial_temp']
        steps = schedule['steps']
        cooling_rate = schedule['cooling_rate']

        original_print("Starting annealing. Initial Energy: {0:.4f}, Temp: {1:.4f}".format(current_energy, temp))

        for i in range(steps):
            proposed_state = np.copy(current_state)
            flip_index = np.random.randint(0, len(current_state))
            proposed_state[flip_index] *= -1

            proposed_energy = energy_function(proposed_state)
            
            delta_energy = proposed_energy - current_energy

            if delta_energy < 0 or np.random.rand() < np.exp(-delta_energy / (temp + 1e-9)):
                current_state = proposed_state
                current_energy = proposed_energy

                if current_energy < best_energy:
                    best_state = np.copy(current_state)
                    best_energy = current_energy
            
            temp *= cooling_rate

        original_print("Finished annealing. Best Energy Found: {0:.4f}".format(best_energy))
        
        # --- Machine-Readable Final State Output ---
        final_state_str = ', '.join(map(str, best_state.astype(int)))
        original_print("[FINAL_STATE]: [{0}]".format(final_state_str))
        
        return best_state.tolist()
    except Exception as e:
        original_print("Error in simulate_annealing: {0}".format(e))
        return [-1, -1, -1, -1]
def maxcut_model(r0, r1, r2, r3, r4, r5, r6, r7):
    r8 = 0.000000
    r9 = 1.000000
    r10 = r9 * r0
    r11 = r10 * r1
    r12 = r8 + r11
    r13 = 1.000000
    r14 = r13 * r0
    r15 = r14 * r5
    r16 = r12 + r15
    r17 = 1.000000
    r18 = r17 * r0
    r19 = r18 * r6
    r20 = r16 + r19
    r21 = 1.000000
    r22 = r21 * r0
    r23 = r22 * r7
    r24 = r20 + r23
    r25 = 1.000000
    r26 = r25 * r1
    r27 = r26 * r2
    r28 = r24 + r27
    r29 = 1.000000
    r30 = r29 * r1
    r31 = r30 * r4
    r32 = r28 + r31
    r33 = 1.000000
    r34 = r33 * r2
    r35 = r34 * r3
    r36 = r32 + r35
    r37 = 1.000000
    r38 = r37 * r2
    r39 = r38 * r4
    r40 = r36 + r39
    r41 = 1.000000
    r42 = r41 * r2
    r43 = r42 * r5
    r44 = r40 + r43
    r45 = 1.000000
    r46 = r45 * r2
    r47 = r46 * r6
    r48 = r44 + r47
    r49 = 1.000000
    r50 = r49 * r2
    r51 = r50 * r7
    r52 = r48 + r51
    r53 = 1.000000
    r54 = r53 * r3
    r55 = r54 * r4
    r56 = r52 + r55
    r57 = 1.000000
    r58 = r57 * r4
    r59 = r58 * r5
    r60 = r56 + r59
    r61 = 1.000000
    r62 = r61 * r5
    r63 = r62 * r6
    r64 = r60 + r63
    r65 = 1.000000
    r66 = r65 * r6
    r67 = r66 * r7
    r68 = r64 + r67
    return r68

def main():
    r69 = 5.000000
    r70 = 0.950000
    r71 = 3000
    _wrapper_for_maxcut_model = lambda spins: maxcut_model(spins[0], spins[1], spins[2], spins[3], spins[4], spins[5], spins[6], spins[7])
    r72 = simulate_annealing(energy_function=_wrapper_for_maxcut_model, initial_state=[-1, -1, 1, 1, 1, 1, -1, -1], schedule={'initial_temp': r69, 'cooling_rate': r70, 'steps': r71})


if __name__ == '__main__':
    try:
        original_print('ThermoLang Python Simulation Starting')
        result = main()
        original_print('Simulation completed successfully')
        original_print('Final result:', result)
    except Exception as e:
        original_print('Error in simulation:')
        import traceback
        traceback.print_exc()
