#include "thermolang/codegen/CodeGenerator.h"
#include "thermolang/ir/ThermoIR.h"

namespace thermolang::codegen
{

    std::string SimulationCodeGenerator::generate(const std::vector<std::unique_ptr<ir::FunctionIR>> &program)
    {
        program_ir_ = &program;
        ss_.str("");
        ss_ << "# Generated by ThermoLang Compiler\n";
        ss_ << "import numpy as np\n";
        ss_ << "import sys\n\n";

        // Save original print and create debug_print but don't override print
        ss_ << "original_print = print  # Save Python's print function\n";
        ss_ << "def debug_print(*args, **kwargs):\n";
        ss_ << "    original_print(*args, **kwargs)\n";
        ss_ << "    sys.stdout.flush()\n\n";

        // --- Simulation Runtime ---
        ss_ << R"PY(
def simulate_annealing(energy_function, initial_state, schedule):
    """
    Performs a simulated annealing run.
    """
    try:
        current_state = np.array(initial_state, dtype=np.float32)
        current_energy = energy_function(current_state)

        best_state = np.copy(current_state)
        best_energy = current_energy

        temp = schedule['initial_temp']
        steps = schedule['steps']
        cooling_rate = schedule['cooling_rate']

        original_print("Starting annealing. Initial Energy: {0:.4f}, Temp: {1:.4f}".format(current_energy, temp))

        for i in range(steps):
            proposed_state = np.copy(current_state)
            flip_index = np.random.randint(0, len(current_state))
            proposed_state[flip_index] *= -1

            proposed_energy = energy_function(proposed_state)
            
            delta_energy = proposed_energy - current_energy

            if delta_energy < 0 or np.random.rand() < np.exp(-delta_energy / (temp + 1e-9)):
                current_state = proposed_state
                current_energy = proposed_energy

                if current_energy < best_energy:
                    best_state = np.copy(current_state)
                    best_energy = current_energy
            
            temp *= cooling_rate

        original_print("Finished annealing. Best Energy Found: {0:.4f}".format(best_energy))
        
        # --- Machine-Readable Final State Output ---
        final_state_str = ', '.join(map(str, best_state.astype(int)))
        original_print("[FINAL_STATE]: [{0}]".format(final_state_str))
        
        return best_state.tolist()
    except Exception as e:
        original_print("Error in simulate_annealing: {0}".format(e))
        return [-1, -1, -1, -1]
)PY";

        // Generate all function definitions FIRST
        for (const auto &func : program)
        {
            generate_function(*func);
        }

        ss_ << "\nif __name__ == '__main__':\n";
        ss_ << "    try:\n";
        ss_ << "        original_print('ThermoLang Python Simulation Starting')\n";
        ss_ << "        result = main()\n";
        ss_ << "        original_print('Simulation completed successfully')\n";
        ss_ << "        original_print('Final result:', result)\n";
        ss_ << "    except Exception as e:\n";
        ss_ << "        original_print('Error in simulation:')\n";
        ss_ << "        import traceback\n";
        ss_ << "        traceback.print_exc()\n";

        return ss_.str();
    }
    std::string format_python_list(const std::vector<double> &vec)
    {
        std::stringstream ss;
        ss << "[";
        for (size_t i = 0; i < vec.size(); ++i)
        {
            ss << vec[i] << (i == vec.size() - 1 ? "" : ", ");
        }
        ss << "]";
        return ss.str();
    }

    std::string format_python_matrix(const std::vector<std::vector<double>> &mat)
    {
        std::stringstream ss;
        ss << "[";
        for (size_t i = 0; i < mat.size(); ++i)
        {
            ss << format_python_list(mat[i]) << (i == mat.size() - 1 ? "" : ", ");
        }
        ss << "]";
        return ss.str();
    }

    void SimulationCodeGenerator::generate_function(const ir::FunctionIR &function)
    {
        std::string func_name = function.name;
        if (func_name == "print")
        {
            func_name = "thermo_print";
        }
        ss_ << "def " << function.name << "(";
        for (size_t i = 0; i < function.parameters.size(); ++i)
        {
            ss_ << function.parameters[i] << (i == function.parameters.size() - 1 ? "" : ", ");
        }
        ss_ << "):\n";
        indent_level_++;

        if (function.basic_blocks.empty() || function.basic_blocks[0]->instructions.empty())
        {
            indent();
            ss_ << "pass\n";
        }
        else
        {
            for (const auto &block : function.basic_blocks)
            {
                for (const auto &instr : block->instructions)
                {
                    generate_instruction(*instr);
                }
            }
        }

        indent_level_--;
        ss_ << "\n";
    }

    std::string SimulationCodeGenerator::operand_to_string(const ir::Operand &op)
    {
        if (std::holds_alternative<std::string>(op))
            return std::get<std::string>(op);
        if (std::holds_alternative<int64_t>(op))
            return std::to_string(std::get<int64_t>(op));
        if (std::holds_alternative<double>(op))
            return std::to_string(std::get<double>(op));
        if (std::holds_alternative<bool>(op))
            return std::get<bool>(op) ? "True" : "False";
        return "None";
    }

    void SimulationCodeGenerator::generate_instruction(const ir::Instruction &instr)
    {
        indent();
        if (auto i = dynamic_cast<const ir::LoadConstInstr *>(&instr))
        {
            ss_ << i->result_reg << " = " << operand_to_string(i->value) << "\n";
        }
        else if (auto i = dynamic_cast<const ir::BinaryOpInstr *>(&instr))
        {
            char op_char = ' ';
            switch (i->opcode)
            {
            case ir::OpCode::ADD:
                op_char = '+';
                break;
            case ir::OpCode::SUB:
                op_char = '-';
                break;
            case ir::OpCode::MUL:
                op_char = '*';
                break;
            case ir::OpCode::DIV:
                op_char = '/';
                break;
            default:
                break;
            }
            ss_ << i->result_reg << " = " << operand_to_string(i->arg1) << " " << op_char << " " << operand_to_string(i->arg2) << "\n";
        }
        else if (auto i = dynamic_cast<const ir::CallInstr *>(&instr))
        {
            if (i->callee_name == "thermal_anneal" && i->args.size() == 4)
            {
                std::string energy_func_name = operand_to_string(i->args[0]);

                size_t num_params = 0;
                for (const auto &func : *program_ir_)
                {
                    if (func->name == energy_func_name)
                    {
                        num_params = func->parameters.size();
                        break;
                    }
                }

                if (num_params == 0)
                {
                    ss_ << "# ERROR: Could not find energy function '" << energy_func_name << "' to create wrapper.\n";
                    return;
                }

                std::string wrapper_name = "_wrapper_for_" + energy_func_name;
                ss_ << wrapper_name << " = lambda spins: " << energy_func_name << "(";
                for (size_t p = 0; p < num_params; ++p)
                {
                    ss_ << "spins[" << p << "]" << (p == num_params - 1 ? "" : ", ");
                }
                ss_ << ")\n";
                indent();

                if (i->result_reg)
                    ss_ << *i->result_reg << " = ";
                ss_ << "simulate_annealing(energy_function=" << wrapper_name
                    << ", initial_state=[1.0] * " << num_params
                    << ", schedule={'initial_temp': " << operand_to_string(i->args[1])
                    << ", 'cooling_rate': " << operand_to_string(i->args[2])
                    << ", 'steps': " << operand_to_string(i->args[3]) << "})\n";
            }
            else if (i->callee_name == "print")
            {
                ss_ << "# print call suppressed\n";
            }
            else
            {
                if (i->result_reg)
                    ss_ << *i->result_reg << " = ";
                ss_ << i->callee_name << "(";
                for (size_t k = 0; k < i->args.size(); ++k)
                {
                    ss_ << operand_to_string(i->args[k]) << (k == i->args.size() - 1 ? "" : ", ");
                }
                ss_ << ")\n";
            }
        }
        else if (auto i = dynamic_cast<const ir::DiscreteEBMInstr *>(&instr))
        {
            // This instruction contains the full problem definition. We generate a calculation
            // that uses the J matrix and h vector directly.
            ss_ << "J = np.array(" << format_python_matrix(i->J_matrix) << ")\n";
            indent();
            ss_ << "h = np.array(" << format_python_list(i->h_vector) << ")\n";
            indent();
            // The input spins are passed as function arguments (r0, r1, ...)
            ss_ << "s = np.array([";
            for (size_t s_idx = 0; s_idx < i->spins.size(); ++s_idx)
            {
                ss_ << operand_to_string(i->spins[s_idx]) << (s_idx == i->spins.size() - 1 ? "" : ", ");
            }
            ss_ << "])\n";

            indent();
            // The standard Discrete EBM calculation
            ss_ << "coupling_energy = 0.5 * np.dot(s.T, np.dot(J, s))\n";
            indent();
            ss_ << "field_energy = np.dot(h.T, s)\n";
            indent();
            ss_ << i->result_reg << " = -(coupling_energy + field_energy)\n";
        }
        else if (auto i = dynamic_cast<const ir::ReturnInstr *>(&instr))
        {
            ss_ << "return " << (i->return_value ? operand_to_string(*i->return_value) : "") << "\n";
        }
        else
        {
            ss_ << "# Unhandled IR: " << instr.toString() << "\n";
        }
    }

    void SimulationCodeGenerator::indent()
    {
        for (int i = 0; i < indent_level_; ++i)
        {
            ss_ << "    ";
        }
    }

}