#include "thermolang/codegen/SPUCodeGenerator.h"
#include "thermolang/hardware/SPUController.h" // For Matrix/Vector types
#include <iomanip>

namespace thermolang::codegen
{

    std::string SPUCodeGenerator::format_cpp_vector(const thermolang::hardware::Vector &vec)
    {
        std::stringstream out;
        out << "{";
        for (size_t i = 0; i < vec.size(); ++i)
        {
            out << vec[i] << (i == vec.size() - 1 ? "" : ", ");
        }
        out << "}";
        return out.str();
    }

    std::string SPUCodeGenerator::format_cpp_matrix(const thermolang::hardware::Matrix &mat)
    {
        std::stringstream out;
        out << "{";
        for (size_t i = 0; i < mat.size(); ++i)
        {
            out << format_cpp_vector(mat[i]) << (i == mat.size() - 1 ? "" : ", ");
        }
        out << "}";
        return out.str();
    }
    template <typename T>
    T get_const_from_operand(const ir::Operand &op, const std::vector<std::unique_ptr<ir::FunctionIR>> &program)
    {
        if (const T *val = std::get_if<T>(&op))
        {
            return *val; // It's already a literal value
        }
        if (const std::string *reg_name = std::get_if<std::string>(&op))
        {
            // It's a register name, find its defining LoadConstInstr
            for (const auto &func : program)
            {
                for (const auto &block : func->basic_blocks)
                {
                    for (const auto &instr : block->instructions)
                    {
                        if (auto *load = dynamic_cast<ir::LoadConstInstr *>(instr.get()))
                        {
                            if (load->result_reg == *reg_name)
                            {
                                if (const T *loaded_val = std::get_if<T>(&load->value))
                                {
                                    return *loaded_val;
                                }
                            }
                        }
                    }
                }
            }
        }
        // Return a default value if not found
        return T{};
    }
    std::string SPUCodeGenerator::generate(const std::vector<std::unique_ptr<ir::FunctionIR>> &program)
    {
        ss_.str(""); // Clear the stream

        // --- Find the key IR instructions ---
        const ir::CallInstr *anneal_call = nullptr;
        const ir::IsingHamiltonianInstr *ising_instr = nullptr;

        const ir::FunctionIR *main_func = nullptr;
        for (const auto &func : program)
        {
            if (func->name == "main")
            {
                main_func = func.get();
                break;
            }
        }
        if (!main_func)
            return "// ERROR: Could not find main function.\n";

        // Find the thermal_anneal call in main
        for (const auto &block : main_func->basic_blocks)
        {
            for (const auto &instr : block->instructions)
            {
                if (auto *call = dynamic_cast<ir::CallInstr *>(instr.get()))
                {
                    if (call->callee_name == "thermal_anneal")
                    {
                        anneal_call = call;
                        break;
                    }
                }
            }
            if (anneal_call)
                break;
        }
        if (!anneal_call)
            return "// ERROR: Could not find thermal_anneal call in main.\n";

        // Find the energy function definition
        std::string energy_func_name = std::get<std::string>(anneal_call->args[0]);
        for (const auto &func : program)
        {
            if (func->name == energy_func_name)
            {
                // An Ising-optimized function should have exactly two instructions: IsingHamiltonian and Return.
                if (func->basic_blocks.size() == 1 && func->basic_blocks[0]->instructions.size() == 2)
                {
                    ising_instr = dynamic_cast<ir::IsingHamiltonianInstr *>(func->basic_blocks[0]->instructions[0].get());
                }
                break;
            }
        }
        if (!ising_instr)
            return "// ERROR: Could not find optimized IsingHamiltonian instruction.\n";

        // --- Generate C++ Code ---
        ss_ << "// Generated by the ThermoLang Compiler for the SPU target\n";
        ss_ << "#include <iostream>\n";
        ss_ << "#include \"thermolang/hardware/SPUController.h\"\n\n";

        ss_ << "int main() {\n";
        ss_ << "    // 1. Define the hardware configuration for the Ising model problem.\n";
        ss_ << "    thermolang::hardware::SPUConfig config;\n";
        ss_ << "    config.coupling_matrix = " << format_cpp_matrix(ising_instr->J_matrix) << ";\n";
        ss_ << "    config.local_field = " << format_cpp_vector(ising_instr->h_vector) << ";\n";

        // Note: We are now using the optimized schedule values
        ss_ << "    config.initial_temp = " << get_const_from_operand<double>(anneal_call->args[1], program) << ";\n";
        ss_ << "    config.cooling_rate = " << get_const_from_operand<double>(anneal_call->args[2], program) << ";\n";
        ss_ << "    config.steps = " << get_const_from_operand<int64_t>(anneal_call->args[3], program) << ";\n\n";

        ss_ << "    // 2. Initialize the hardware controller with the configuration.\n";
        ss_ << "    thermolang::hardware::SPUController controller(config);\n\n";

        ss_ << "    // 3. Execute the annealing process.\n";
        ss_ << "    thermolang::hardware::ExecutionResult result = controller.execute();\n\n";

        ss_ << "    // 4. Print the results.\n";
        ss_ << "    std::cout << \"--- SPU Execution Result ---\" << std::endl;\n";
        ss_ << "    std::cout << \"Final Energy: \" << result.final_energy << std::endl;\n";
        ss_ << "    std::cout << \"Final Spin State: {\";\n";
        ss_ << "    for(size_t i = 0; i < result.final_state.size(); ++i) {\n";
        ss_ << "        std::cout << result.final_state[i] << (i == result.final_state.size() - 1 ? \"\" : \", \");\n";
        ss_ << "    }\n";
        ss_ << "    std::cout << \"}\" << std::endl;\n\n";

        ss_ << "    return 0;\n";
        ss_ << "}\n";

        return ss_.str();
    }

} // namespace thermolang::codegen