#include "thermolang/codegen/ThrmlCodeGenerator.h"
#include <iomanip>
#include <stdexcept>
#include <sstream>

namespace thermolang::codegen
{
    // Helper to get a constant value from an operand by tracing back to its definition.
    // This is necessary because the IR might pass registers instead of immediate values.
    template <typename T>
    T get_const_val(const ir::Operand &op, const std::vector<std::unique_ptr<ir::FunctionIR>> &program)
    {
        if (const T *val = std::get_if<T>(&op))
        {
            return *val; // It's already a literal value
        }
        if (const std::string *reg_name = std::get_if<std::string>(&op))
        {
            // It's a register name, find its defining LoadConstInstr
            for (const auto &func : program)
            {
                for (const auto &block : func->basic_blocks)
                {
                    for (const auto &instr : block->instructions)
                    {
                        if (auto *load = dynamic_cast<ir::LoadConstInstr *>(instr.get()))
                        {
                            if (load->result_reg == *reg_name)
                            {
                                if (const T *loaded_val = std::get_if<T>(&load->value))
                                {
                                    return *loaded_val;
                                }
                            }
                        }
                    }
                }
            }
        }
        // If the value cannot be resolved at compile time, throw an error.
        throw std::runtime_error("Could not resolve constant value from IR for thrml codegen.");
    }

    std::string ThrmlCodeGenerator::format_python_list(const std::vector<double>& vec)
    {
        std::stringstream out;
        out << "[";
        for (size_t i = 0; i < vec.size(); ++i)
        {
            out << vec[i] << (i == vec.size() - 1 ? "" : ", ");
        }
        out << "]";
        return out.str();
    }

    std::string ThrmlCodeGenerator::generate(const std::vector<std::unique_ptr<ir::FunctionIR>> &program)
    {
        std::stringstream ss;

        const ir::CallInstr* anneal_call = nullptr;
        const ir::DiscreteEBMInstr* ebm_instr = nullptr;
        const ir::FunctionIR* main_func = nullptr;

        // 1. Find the main function to locate the top-level call.
        for(const auto& func : program) {
            if(func->name == "main") {
                main_func = func.get();
                break;
            }
        }
        if (!main_func) return "# ERROR: Could not find main function in IR.\n";
        
        // 2. Find the thermal_anneal call instruction within main.
        for (const auto& block : main_func->basic_blocks) {
            for (const auto& instr : block->instructions) {
                if (auto* call = dynamic_cast<ir::CallInstr*>(instr.get())) {
                    if (call->callee_name == "thermal_anneal") {
                        anneal_call = call;
                        break;
                    }
                }
            }
            if (anneal_call) break;
        }
        if (!anneal_call) return "# ERROR: Could not find thermal_anneal call in main function.\n";

        // 3. Find the definition of the energy function passed to the anneal call.
        std::string energy_func_name = std::get<std::string>(anneal_call->args[0]);
        for (const auto& func : program) {
            if (func->name == energy_func_name) {
                // The optimized energy function should contain a single DiscreteEBMInstr.
                if (!func->basic_blocks.empty() && !func->basic_blocks[0]->instructions.empty()) {
                    ebm_instr = dynamic_cast<ir::DiscreteEBMInstr*>(func->basic_blocks[0]->instructions[0].get());
                }
                break;
            }
        }
        if (!ebm_instr) return "# ERROR: Could not find optimized DiscreteEBMInstr for the energy function.\n";

        int num_spins = ebm_instr->spins.size();

        ss << "# Generated by ThermoLang Compiler for the 'thrml' backend\n";
        ss << "# This script uses the thrml library from Extropic AI.\n";
        ss << "import jax\n";
        ss << "import jax.numpy as jnp\n";
        ss << "from thrml import SpinNode, Block, SamplingSchedule, sample_states\n";
        ss << "from thrml.models import IsingEBM, IsingSamplingProgram, hinton_init\n\n";

        ss << "def main():\n";
        ss << "    print('--- Setting up thrml simulation ---')\n";
        ss << "    nodes = [SpinNode() for _ in range(" << num_spins << ")]\n";
        ss << "    edges = []\n";
        ss << "    weights_list = []\n\n";

        ss << "    biases = jnp.array(" << format_python_list(ebm_instr->h_vector) << ", dtype=jnp.float32)\n";

        ss << "    # Reconstructing graph from J matrix\n";
        const auto& J = ebm_instr->J_matrix;
        for (size_t i = 0; i < J.size(); ++i) {
            for (size_t j = i + 1; j < J[i].size(); ++j) {
                if (std::abs(J[i][j]) > 1e-9) { // Only add non-zero couplings
                    ss << "    edges.append((nodes[" << i << "], nodes[" << j << "]))\n";
                    ss << "    weights_list.append(" << J[i][j] << ")\n";
                }
            }
        }
        ss << "    weights = jnp.array(weights_list, dtype=jnp.float32)\n\n";

        // Get annealing parameters from the IR
        double initial_temp = get_const_val<double>(anneal_call->args[1], program);
        int64_t steps = get_const_val<int64_t>(anneal_call->args[3], program);

        ss << "    beta = jnp.array(1.0 / " << initial_temp << ", dtype=jnp.float32) # Note: thrml uses beta (inverse temp)\n";
        ss << "    model = IsingEBM(nodes, edges, biases, weights, beta)\n\n";
        
        ss << "    # Using a simple 2-coloring scheme for block Gibbs sampling\n";
        ss << "    free_blocks = [Block(nodes[::2]), Block(nodes[1::2])]\n";
        ss << "    program = IsingSamplingProgram(model, free_blocks, clamped_blocks=[])\n\n";

        ss << "    key = jax.random.key(0)\n";
        ss << "    k_init, k_samp = jax.random.split(key, 2)\n";
        ss << "    # Initialize state using Hinton's method\n";
        ss << "    init_state = hinton_init(k_init, model, free_blocks, ())\n";
        
        // A simple mapping from our steps to thrml's schedule.
        // A more advanced compiler could be smarter about this.
        ss << "    schedule = SamplingSchedule(n_warmup=" << steps / 2 
           << ", n_samples=1, steps_per_sample=" << steps / 2 << ")\n\n";
        
        ss << "    print(f'--- Running thrml simulation for {schedule.n_warmup + schedule.n_samples * schedule.steps_per_sample} total steps ---')\n";
        ss << "    samples = sample_states(k_samp, program, schedule, init_state, [], [Block(nodes)])\n\n";

        ss << "    final_state = samples[0][0]\n";
        ss << "    # Convert boolean spins back to {-1, 1} for standardized output\n";
        ss << "    final_state_int = 2 * final_state.astype(jnp.int8) - 1\n";
        ss << "    final_state_str = ', '.join(map(str, final_state_int.tolist()))\n";
        ss << "    print(f'Final state found. Use [FINAL_STATE] for automated benchmarks.')\n";
        ss << "    print(f'[FINAL_STATE]: [{final_state_str}]')\n";
        ss << "    return final_state_int\n\n";

        ss << "if __name__ == '__main__':\n";
        ss << "    main()\n";

        return ss.str();
    }
} // namespace thermolang::codegen