`default_nettype none
`timescale 1ns / 1ps

module tb_spu_array;

    parameter DATA_WIDTH = 16;
    parameter FRAC_BITS  = 12;
    parameter CLK_PERIOD = 10;
    parameter GRID_SIZE = 4;
    // Config file reading params
    parameter TOTAL_CONFIG_WORDS = GRID_SIZE * GRID_SIZE * 5; 

    reg clk;
    reg rst_n;
    
    // Config Interface
    reg [3:0]  config_addr_row;
    reg [3:0]  config_addr_col;
    reg signed [DATA_WIDTH-1:0] config_data_in_h, config_data_in_j_north, config_data_in_j_south, config_data_in_j_east, config_data_in_j_west;
    reg        config_we;
    reg        [DATA_WIDTH-1:0] temperature;
    
    // Outputs
    wire signed [1:0] spin_out_grid [0:3][0:3];
    // (Wire definitions for flattened outputs to keep Verilog happy)
    wire signed [1:0] so00, so01, so02, so03, so10, so11, so12, so13, so20, so21, so22, so23, so30, so31, so32, so33;
    
    // Map flattened outputs to array for easier printing
    assign spin_out_grid[0][0] = so00; assign spin_out_grid[0][1] = so01; assign spin_out_grid[0][2] = so02; assign spin_out_grid[0][3] = so03;
    assign spin_out_grid[1][0] = so10; assign spin_out_grid[1][1] = so11; assign spin_out_grid[1][2] = so12; assign spin_out_grid[1][3] = so13;
    assign spin_out_grid[2][0] = so20; assign spin_out_grid[2][1] = so21; assign spin_out_grid[2][2] = so22; assign spin_out_grid[2][3] = so23;
    assign spin_out_grid[3][0] = so30; assign spin_out_grid[3][1] = so31; assign spin_out_grid[3][2] = so32; assign spin_out_grid[3][3] = so33;

    // Instantiate DUT (Device Under Test)
    spu_array_4x4 #(.DATA_WIDTH(DATA_WIDTH), .FRAC_BITS(FRAC_BITS)) dut (
        .clk(clk), .rst_n(rst_n),
        .config_addr_row(config_addr_row), .config_addr_col(config_addr_col),
        .config_data_in_h(config_data_in_h), .config_data_in_j_north(config_data_in_j_north), 
        .config_data_in_j_south(config_data_in_j_south), .config_data_in_j_east(config_data_in_j_east), 
        .config_data_in_j_west(config_data_in_j_west), .config_we(config_we),
        .temperature(temperature),
        // No random inputs!
        .spin_out_0_0(so00), .spin_out_0_1(so01), .spin_out_0_2(so02), .spin_out_0_3(so03),
        .spin_out_1_0(so10), .spin_out_1_1(so11), .spin_out_1_2(so12), .spin_out_1_3(so13),
        .spin_out_2_0(so20), .spin_out_2_1(so21), .spin_out_2_2(so22), .spin_out_2_3(so23),
        .spin_out_3_0(so30), .spin_out_3_1(so31), .spin_out_3_2(so32), .spin_out_3_3(so33)
    );

    // Clock Generation
    always #(CLK_PERIOD / 2) clk = ~clk;
    
    // File reading vars
    real initial_temp_real, cooling_rate_real, temp_real;
    integer anneal_steps, file_handle, mem_idx, r, c, step;
    reg [DATA_WIDTH-1:0] problem_mem [0:TOTAL_CONFIG_WORDS-1];
    integer dummy_fscan_ret;

    function real fixed_to_real(input signed [DATA_WIDTH-1:0] val);
        fixed_to_real = val / (1.0 * (1 << FRAC_BITS));
    endfunction
    
    task display_spin_grid;
        begin
            $display("--- Spin Grid at time %t ---", $time);
            for (r = 0; r < GRID_SIZE; r = r + 1) begin
                $write("  ROW %d: ", r);
                for (c = 0; c < GRID_SIZE; c = c + 1) begin
                    if (spin_out_grid[r][c] == 1) $write("+ "); else $write("- ");
                end
                $write("\n");
            end
            $display("------------------------------");
        end
    endtask
    
    initial begin
        // 1. Initialize
        clk=0; rst_n=0; config_we=0; 
        // Reset hold time
        #(CLK_PERIOD*20); 
        rst_n=1;
        
        // 2. Load problem config from file (Generated by ThermoLang compiler)
        // Make sure these files exist or create dummy ones!
        file_handle = $fopen("3_ising_solver_schedule.txt", "r");
        if (file_handle == 0) begin
             $display("WARNING: Could not open schedule file. Using defaults.");
             initial_temp_real = 10.0; cooling_rate_real = 0.99; anneal_steps = 1000;
        end else begin
            dummy_fscan_ret = $fscanf(file_handle, "%*s %f", initial_temp_real); 
            dummy_fscan_ret = $fscanf(file_handle, "%*s %f", cooling_rate_real);
            dummy_fscan_ret = $fscanf(file_handle, "%*s %d", anneal_steps);
            $fclose(file_handle);
        end
        
        // Load Mem
        $readmemh("3_ising_solver_config.mem", problem_mem);
        
        // 3. Program the Array (Write Config)
        $display("[TB] Programming Array...");
        mem_idx = 0; config_we = 1;
        for(r=0; r<GRID_SIZE; r=r+1) begin
            for(c=0; c<GRID_SIZE; c=c+1) begin
                config_addr_row<=r; config_addr_col<=c;
                config_data_in_h<=problem_mem[mem_idx]; mem_idx=mem_idx+1;
                config_data_in_j_north<=problem_mem[mem_idx]; mem_idx=mem_idx+1;
                config_data_in_j_south<=problem_mem[mem_idx]; mem_idx=mem_idx+1;
                config_data_in_j_east<=problem_mem[mem_idx]; mem_idx=mem_idx+1;
                config_data_in_j_west<=problem_mem[mem_idx]; mem_idx=mem_idx+1;
                #(CLK_PERIOD);
            end
        end
        config_we = 0;
        
        // 4. Run Annealing
        temperature = initial_temp_real * (1 << FRAC_BITS);
        $display("[TB] Starting Anneal. T_start=%f, Steps=%d", initial_temp_real, anneal_steps);
        
        for (step = 0; step < anneal_steps; step = step + 1) begin
            
            // Only update temperature, NO RANDOM NUMBER FEEDING needed!
            temp_real = fixed_to_real(temperature);
            temperature <= (temp_real * cooling_rate_real) * (1 << FRAC_BITS);
            
            // Log occasionally
            if (step % (anneal_steps/5) == 0) begin
                $display("[TB] Step %d, Temp = %f", step, fixed_to_real(temperature));
                display_spin_grid();
            end
            
            // Wait a bit for the ring oscillators to do their chaotic magic
            #(CLK_PERIOD * 10);
        end
        
        $display("[TB] Annealing finished."); display_spin_grid();
        $write("[FINAL_STATE]: [");
        for(r=0; r<GRID_SIZE; r=r+1) for(c=0; c<GRID_SIZE; c=c+1) begin
            if (spin_out_grid[r][c] == 1) $write("1"); else $write("-1");
            if (r < GRID_SIZE - 1 || c < GRID_SIZE - 1) $write(", ");
        end
        $write("]\n");
        $finish;
    end
endmodule